
skillMetadata:
  sections:
    - name: My Streams
      fields:
        - type: label
          label: List the streams you'd like to access
        - name: stream1
          type: text
          label: Stream 1
          value: "WAMC http://playerservices.streamtheworld.com/api/livestream-redirect/WAMCHD2.mp3"
        - name: stream2
          type: text
          label: Stream 2
          value: ""
