
skillMetadata:
  sections:
    - name: Usage
      fields:
        - type: label
          label: Say "stream WAMC" or "stop streaming" or "cancel streaming".
        - name: willing_to_share
          type: checkbox
          label: Make my streaming entries avialable to other users.
          value: "false"
    - name: Streams
      fields:
        - type: label
          label: Enter your own streams below using the first entry as a pattern.
        - name: stream1
          type: text
          label: Stream 1
          value: "WAMC,http://playerservices.streamtheworld.com/api/livestream-redirect/WAMCHD2.mp3"
        - name: stream2
          type: text
          label: Stream 2
          value: "empty_record"
